### ISSUE TITLE
Footer looks bad on empty discover page

### ISSUE THREAD

**Issue by tbantle22** [dolthub/doltlab-issues#12]
<img width="856" alt="doltlab-homepage" src="https://user-images.githubusercontent.com/29443194/149582553-fbcd607e-54de-447b-9342-e44bb0172b91.png">

The logo should sit in the blue part under the diagonal

**Comment by coffeegoddd** [comment]
Fixed in https://github.com/dolthub/doltlab-issues/releases/tag/v0.3.0
