### ISSUE TITLE
Enable external storage for Doltlab

### ISSUE THREAD

**Issue by snorrefjellvang** [dolthub/doltlab-issues#37]
Currently, a Doltlab instance only supports storage on the host it is running on. It would be nice to be able to set an external databse service to store the data.

**Comment by CooperXxx** [comment]
+1

**Comment by timsehn** [comment]
This is an enterprise feature we are soon shipping.

**Comment by coffeegoddd** [comment]
Supported for DoltLab Enterprise in v2.1.6
