### ISSUE TITLE
api token error

### ISSUE THREAD

**Issue by pirimoglu** [dolthub/doltlab-issues#62]
Hi,

After upgrade doltlab, we are now getting below error. What is the reason of this error, it is not understandable. Can you help?

`{"query_execution_status":"Error","query_execution_message":"apitoken_db: API Token with matching ID not found","repository_owner":"xxx","repository_name":"yyy","commit_ref":"main","sql_query":"SHOW FULL TABLES WHERE Table_Type = 'BASE TABLE'","schema":[],"rows":[]}`

**Comment by coffeegoddd** [comment]
@pirimoglu this bug is fixed in [DoltLab v1.0.3](https://github.com/dolthub/doltlab-issues/releases/tag/v1.0.3), sorry for the inconvenience!
