### ISSUE TITLE
wrong url in the header?

### ISSUE THREAD

**Issue by chicco785** [dolthub/doltlab-issues#68]
Databases link points to `localhost:3000/discover` while it should point to `http://localhost/discover`

![image](https://github.com/dolthub/doltlab-issues/assets/777218/9ef1bfcf-d18a-40c8-a53b-9653ebd138fb)

**Comment by coffeegoddd** [comment]
@chicco785 are you using `localhost` as the `HOST_IP`? If so, I think you're hitting a special case in our code we use for local DoltHub development to correctly route links, but doesn't really work for the DoltLab case. I'm a bit surprised this works at all as DoltLab runs within a Docker network, which isn't able to resolve `localhost`.

Can you tell us more about your use-case and hardware limitations?

**Comment by chicco785** [comment]
> @chicco785 are you using `localhost` as the `HOST_IP`? If so, I think you're hitting a special case in our code we use for local DoltHub development to correctly route links, but doesn't really work for the DoltLab case. I'm a bit surprised this works at all as DoltLab runs within a Docker network, which isn't able to resolve `localhost`.
> 
> Can you tell us more about your use-case and hardware limitations?

initially I have been using `localhost` as HOST_IP, now I moved to the IP of the machine (i.e., `192.168.1.20`), and same result.

At the time being I am just trying to test doltlab. We are looking for a solution to manage easily multiple version of a power grid configuration, and testing dolt in this respect. DoltLab could be a nice way to compare version and govern the process of merging changes. Being just a simple test, I was not looking to do anything complex, so I am using my laptop (which is a Mac Book Pro M2).

**Comment by chicco785** [comment]
sorted out, when changing ip, i needed to change also the generated template for envoy ;)
