### ISSUE TITLE
Push to remote branch not working

### ISSUE THREAD

**Issue by rilor2** [dolthub/doltlab-issues#71]
I'm using Doltlab installed on a VM on GCP, the VM has the following ports open:
tcp:22
tcp:80
tcp:3000
tcp:50051
tcp:100
tcp:4321

I tried the two following scenarios: 

Scenarios number 1:

- dolt repository initialized locally
- database created locally and initialized with DML commands 
- tables added and a new commit message is created on the local dolt repository
- database created on Doltlab running on a separate VM 
- `remote` added to the local dolt repository pointing to the repository on the VM
-  when running `dolt push origin main` i get the following:
```
dolt push origin main
Uploaded 379 B of 379 B @ 0 B/s.
error: push failed
cause: unknown push error; rpc error: code = Internal desc = error downloading URL
```

Scenarios number 2:
- database created on DoltLab running on a separate VM
- database cloned locally using the Doltlab remote Url -> i can then clone the remote repository without any issue 
- DML command to add tables to the local database
- tables added and a new commit message is created
- when running `dolt push origin main` i get the same as before

**Comment by coffeegoddd** [comment]
@rilor2 I'm not able to reproduce this error when testing the scenarios you described above on our demo DoltLab instances.

Can you verify that the remote url for both local databases is in the form `http://${HOST_IP}:50051/<owner name>/<db name>`?

You can check this with the following command:

```
dolt remote -v
origin http://doltlab.dolthub.com:50051/admin/test-db
```

Also, can you send the log output of the `doltlabremoteapi` service? You can view the logs with `docker logs doltlab_doltlabremoteapi_1`.

I would expect to see `error downloading URL` in these logs, as well, but with a more clear error message. If you find this in the logs, you can respond here. You can also email me at dustin@dolthub.com .

**Comment by rilor2** [comment]
The issue was related to the VM not able to reach its external ip address, ip that we set as environment variable `HOST_IP`. 
We set up a forwarding rule on the internal firewall and it's now working as expected. 

Thanks

**Comment by Podolyan98** [comment]
@coffeegoddd, I have a similar problem when executing the `dolt push origin main` command

```
doltlabremoteapi_1       | 2024-01-07T11:33:17.318Z     
WARN    storesrv/chunk_store_service.go:870    
error downloading URL   {"grpc.start_time": "2024-01-07T11:32:47Z", "system": "grpc", "span.kind": "server", "grpc.service": "dolt.services.remotesapi.v1alpha1.ChunkStoreService", "grpc.method": "AddTableFiles", "invocation_id": "37b2e885-7a69-4ca3-a346-0b1191504894", "repo": "repositoryOwners/apodolyan/repositories/Test", "name": "users/apodolyan", "email": "apodolyan@example.com", "display": "apodolyan", "auth_method": "client_token", "error": "Get \"http://10.50.0.18:100/617a6e74-25ad-47e4-b193-e59877e69ea0/vj8mkara4qvrgvjnra9at16ru71nfhcb\": dial tcp 10.50.0.18:100: i/o timeout"}
```

I access Doltlab via VPN:

```
dolt remote -v
origin http://10.50.0.18:50051/apodolyan/Test
```

**Comment by coffeegoddd** [comment]
@Podolyan98 can you share more information about your VPN setup? You need to ensure the ports are being forwarded to the DoltLab services. For example, if you `curl -L http://10.50.0.18:100/test` from a host that can reach the DoltLab instance, you should see the request in the logs for `doltlab_doltlabremoteapi_1`.

Do you also use an internal firewall that might be restricting access?

**Comment by bpf120** [comment]
@Podolyan98 , Thanks for giving DoltLab a go! We'd love to learn more about your use case sometime. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.
