### ISSUE TITLE
Install Documentation/Environment Variable Config File Mismatch

### ISSUE THREAD

**Issue by ctorres-intrepid** [dolthub/doltlab-issues#75]
I am looking at the installation documentation at: https://docs.dolthub.com/products/doltlab/installation
Step 3 shows the following environment variables to setup for start-doltlab.sh:

```
export HOST_IP=<Host IP>
export DOLT_PASSWORD=<Password>
export DOLTHUBAPI_PASSWORD=<Password>
export EMAIL_USERNAME=<SMTP Email Username>
export EMAIL_PASSWORD=<SMTP Email Password>
export EMAIL_PORT=<STMP Email Port>
export EMAIL_HOST=<SMTP Email Host>
export NO_REPLY_EMAIL=<An Email Address to Receive No Reply Messages>

# required for DoltLab Enterprise
export DOLTLAB_ENTERPRISE_ONLINE_PRODUCT_CODE=<Product Code>
export DOLTLAB_ENTERPRISE_ONLINE_SHARED_KEY=<Shared Key>
export DOLTLAB_ENTERPRISE_ONLINE_API_KEY=<API Key>
export DOLTLAB_ENTERPRISE_ONLINE_LICENSE_KEY=<License Key>
export DOLTLAB_ENTERPRISE_HARDWARE_ID=<Hardware ID>

# optional, supported in DoltLab >= v1.0.6
export TLS_CERT_CHAIN=<path to TLS certificate chain>
export TLS_PRIVATE_KEY=<path to TLS private key>
```

However the start-doltlab.sh downloaded with the ubuntu-bootstrap.sh has the following environment variables:

```
export HOST_IP
export DOLTLAB_ENTERPRISE_ONLINE_PRODUCT_CODE
export DOLTLAB_ENTERPRISE_ONLINE_SHARED_KEY
export DOLTLAB_ENTERPRISE_ONLINE_API_KEY
export DOLTLAB_ENTERPRISE_ONLINE_LICENSE_KEY
export DOLTLAB_ENTERPRISE_HARDWARE_ID
export AWS_PROFILE
export AWS_REGION
export AWS_SHARED_CREDENTIALS_FILE
export AWS_CONFIG_FILE
export GOOGLE_APPLICATION_CREDENTIALS
export DOLT_BACKUP_URL
```

**Comment by coffeegoddd** [comment]
My apologies, this is expected, although the documentation could have been more clear.

The section outlining the various environment variables in the installation guide is meant to convey that these variables should be set in your shell, not that they should be explicitly referenced/defined in the `./start-doltlab.sh` script.

Out-of-the-box, the script will reference some of them explicitly, but not all. 

I went ahead and updated our documentation with this detail to hopefully clear this up for others. https://github.com/dolthub/docs/pull/1893/files

Thanks for letting us know! Closing this issue for now.
