### ISSUE TITLE
Deployed a Doltlab in a custom URL but its getting erro

### ISSUE THREAD

**Issue by resulraveendran** [dolthub/doltlab-issues#78]

**Comment by timsehn** [comment]
Transferred this to DoltLab issues.

@coffeegoddd can help debug this.

**Comment by resulraveendran** [comment]
The version is envoy-alpine:v1.18-latest -DoltLab 
dolt client I am using latest version

doltlab instance is configured on https://doltlab.nets.com, But the clone url will be http://doltlab.nets.com:50051/resulr/getting_started

 PROXY ADD ONLY FOR 50051,for others I didnt  use any proxy

**Comment by resulraveendran** [comment]
"I would like to know how to create a clone URL."
How to customize  this http://doltlab.nets.com:50051/resulr/getting_started ,

**Comment by resulraveendran** [comment]
"I would like to know how to create a clone URL."
How to customize  this http://doltlab.nets.com:50051/resulr/getting_started ,

**Comment by resulraveendran** [comment]
"I would like to know how to create a clone URL."
How to customize  this http://doltlab.nets.com:50051/resulr/getting_started ,

**Comment by coffeegoddd** [comment]
@resulraveendran I understand now, thanks for explaining... Currently this is not possible with DoltLab `v2.0.9`, as the clone url will always be `HOST_IP:50051`. Even if you run a proxy at `http://doltlab.nets.com/resulr/getting_started` that forwards to `https://doltlab.nets.com:50051/resulr/getting_started`, the DoltLab UI will still render `https://doltlab.nets.com:50051/resulr/getting_started` for the clone url.

I'm currently working on the next DoltLab release which will make custom clone urls much easier for the DoltLab Enterprise edition, and it's possible there's a way to configure the free version of DoltLab to customize the clone url as well, but I will have to test this.

I'll update this issue with the work around for the free tier when the next DoltLab release is out.

**Comment by resulraveendran** [comment]
Issue resolved@thanks for ur suppot
