### ISSUE TITLE
Use custom logo on DoltLab instance is not working for me.

### ISSUE THREAD

**Issue by resulraveendran** [dolthub/doltlab-issues#79]
Hi,

  As I am looking to change my doltlab instance log by using this [document](https://docs.dolthub.com/products/doltlab/administrator#use-custom-logo), But is not working. Does anyone know the issue?
  
  Note: I am using the doltlab version "public.ecr.aws/dolthub/doltlab/dolthub-server:v2.0.8"

**Comment by resulraveendran** [comment]
"ALT_LOGO variable is not set. Defaulting to a blank string  " I am getting this warning when running the ./start-doltlab.sh

**Comment by coffeegoddd** [comment]
@resulraveendran you must be a DoltLab Enterprise client for the custom logo to work, cc @bpf120 who can discuss Enterprise more with you.
