### ISSUE TITLE
add dep installation scripts to this repo and have the `installer` generate them

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/doltlab-issues#81]

**Comment by timsehn** [comment]
The scripts are here:

1. [Ubuntu](https://gist.github.com/coffeegoddd/f6cacad2a6da423ca27cd0bebc67fd80)
2. [CentOS](https://gist.github.com/coffeegoddd/655669b436dbf28d78d5610749350811)

Definitely useful to just download the installer and then have an `installer bootstrap` command.

**Comment by coffeegoddd** [comment]
fixed in DoltLab v2.1.2
