### ISSUE TITLE
Gmail SMTP Does not work even though the connection helper works. 

### ISSUE THREAD

**Issue by timsehn** [dolthub/doltlab-issues#85]
Repro steps:

1. Go to https://myaccount.google.com/security
2. Click 2-step verification and scroll to the bottom and click App Passwords
3. Enter an App Name (I use "DoltLab") and click create.
4. This will give you a password of the form 'xxxx xxxx xxxx xxxx'
5. Copy it somewhere.
6. Go to your Doltlab install and try the SMTP connection help like so:
```sh
ubuntu@ip-10-2-0-24:~/doltlab$ ./smtp_connection_helper --host smtp.gmail.com --port 587 --auth plain --username tim@dolthub.com --password 'xxxx xxxx xxxx xxxx' --from tim@dolthub.com --to tim@dolthub.com
Sending email with auth method: plain
Successfully sent email!
```
It should work.
7. (optional) Make sure you've stopped the Dolt Lab server and cleared the docker volumes if you already had one running:
```sh
./stop.sh
docker system prune -a
docker volume ls -q | xargs docker volume rm
```
8. Now create a fresh DoltLab install with those same credentials.
```sh
./installer --host 54.191.163.60 --smtp-host=smtp.gmail.com --smtp-port=587 --smtp-username=tim@dolthub.com --smtp-password='xxxx xxxx xxxx xxxx' --no-reply-email=tim@dolthub.com
```
9. Start it.
```
./start.sh
```
10. Try to create an account on your instance. It will fail with an authentication error:
<img width="395" alt="image" src="https://github.com/dolthub/doltlab-issues/assets/5376236/f222819e-6e06-4887-a603-e3eed13a85bd">

**Comment by coffeegoddd** [comment]
From what i can tell this is a gmail SMTP server issue and not a DoltLab issue...

**Comment by timsehn** [comment]
Subsequent tries were able to get this to work. The Gmail SMTP server authentication seems flakey.
