### ISSUE TITLE
Easy way to tell whether I'm running my DoltLab in Enterprise mode

### ISSUE THREAD

**Issue by timsehn** [dolthub/doltlab-issues#86]
There is no way to tell once you've started DoltLab with proper Enterprise creds whether it works. I suggest changing the logo to say "DoltLab Enterprise" (unless a custom logo is specified) and add "ENTERPRISE" to the version string at the bottom.

<img width="1439" alt="image" src="https://github.com/dolthub/doltlab-issues/assets/5376236/098f960d-7010-4700-816a-e7ace42ec5de">

**Comment by coffeegoddd** [comment]
Added to DoltLab `v2.1.3`
